// Snapshot the Samadi Supermarket online catalogue (samadisupermarket.com, an Olsera store) into
// src/content/shop.ts so the shop can live on this site. Run again to refresh names, prices and stock.
//   npm run shop:fetch
import { writeFile } from "node:fs/promises";

const BASE = "https://www.samadisupermarket.com";

// Aisles in the store's own order. Promo and "new release" collections only repeat these products.
const collections = [
  ["fruit-vegetables", 144936, "Fruit & Vegetables"],
  ["bakery-pastry-dessert", 144942, "Bakery & Pastry"],
  ["vegan-diary-milk-eggs", 144941, "Dairy, Milk & Eggs"],
  ["vegan-vegetarian-meats", 144938, "Vegan & Vegetarian Meats"],
  ["vegan-vegetarian-cheeses-tapas", 144939, "Cheeses & Tapas"],
  ["meals-soups-salads", 144937, "Meals, Soups & Salads"],
  ["frozen-products", 144951, "Frozen"],
  ["seafood", 266690, "Seafood"],
  ["juices-drinks-coffee-tea", 144944, "Juices, Coffee & Tea"],
  ["detox-drinks-detox-products", 144945, "Detox"],
  ["organic-alcoholic-beverages", 144947, "Organic Wine & Beer"],
  ["cereals-spreads-snacks", 144943, "Cereals, Spreads & Snacks"],
  ["candy-cookies-chips-chocolate", 144950, "Cookies, Chips & Chocolate"],
  ["pasta-rice-worldkitchen", 144948, "Pasta, Rice & World Kitchen"],
  ["spices-seasonings-sauces-oils", 144949, "Spices, Sauces & Oils"],
  ["sembako", 144935, "Pantry Staples"],
  ["herbal-health", 145126, "Herbal & Health"],
  ["velato-ice", 144952, "Velato Gelato"],
  ["bodycare-hygiene", 144953, "Body Care"],
  ["beauty-skin", 175660, "Beauty & Skin"],
  ["household-table-kitchen", 144954, "Household & Kitchen"],
  ["fashion-accessories", 145289, "Fashion & Accessories"],
  ["books-stationary", 144955, "Books & Stationery"],
  ["games", 156967, "Games"],
];

const decode = (s) =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&#0?39;|&apos;/g, "’")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();

async function get(url, tries = 3) {
  for (let i = 1; ; i++) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30000) });
      if (!res.ok) throw new Error(`${res.status}`);
      return await res.text();
    } catch (e) {
      if (i >= tries) throw new Error(`${url}: ${e.message}`);
      await new Promise((r) => setTimeout(r, 1500 * i));
    }
  }
}

function parse(html) {
  const cards = html.split('<div class="card card-product card-plain">').slice(1);
  return cards.flatMap((card) => {
    const link = card.match(/<h4 class="card-title">\s*<a\s+href="([^"]+\/(\d+))">([^<]+)<\/a>/);
    const price = card.match(/price-new">\s*IDR\s*([\d.]+)/);
    if (!link || !price) return [];
    const old = card.match(/price-old">\s*IDR\s*([\d.]+)/);
    const img = card.match(/<img src="([^"]+)"/)?.[1] ?? "";
    return [
      {
        id: link[2],
        name: decode(link[3]),
        price: Number(price[1].replace(/\./g, "")),
        ...(old ? { was: Number(old[1].replace(/\./g, "")) } : {}),
        image: img.includes("no_photo") ? "" : img,
        inStock: !/>\s*Out Of Stock\s*</i.test(card),
      },
    ];
  });
}

const seen = new Set();
const categories = [];
const products = [];

for (const [slug, id, label] of collections) {
  let count = 0;
  for (let page = 1; page < 60; page++) {
    const html = await get(`${BASE}/collection/${slug}/${id}?page=${page}`);
    const items = parse(html);
    const fresh = items.filter((p) => !seen.has(p.id));
    for (const p of fresh) {
      seen.add(p.id);
      products.push({ ...p, category: slug });
      count++;
    }
    // Olsera keeps serving the last page for out-of-range numbers, so stop once nothing new appears.
    if (!items.length || !fresh.length) break;
  }
  if (count) categories.push({ slug, label, count });
  console.log(`${label}: ${count}`);
}

const out = `// Generated by scripts/fetch-shop.mjs from ${BASE} on ${new Date().toISOString().slice(0, 10)}.
// Do not edit by hand — run \`npm run shop:fetch\` to refresh.

export type ShopProduct = {
  id: string;
  name: string;
  /** Price in IDR */
  price: number;
  /** Pre-discount price in IDR, when on promotion */
  was?: number;
  image: string;
  inStock: boolean;
  category: string;
};

export type ShopCategory = { slug: string; label: string; count: number };

export const shopCategories: ShopCategory[] = ${JSON.stringify(categories, null, 2)};

export const shopProducts: ShopProduct[] = ${JSON.stringify(products)};
`;

await writeFile(new URL("../src/content/shop.ts", import.meta.url), out);
console.log(`\n${products.length} products in ${categories.length} categories → src/content/shop.ts`);
