// Turns .assets-raw/ originals into web-ready files in public/images/ and writes
// src/content/media.ts (src, intrinsic size, alt) so pages can reference assets by key.
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { assets } from "./asset-manifest.mjs";

const RAW = path.resolve(".assets-raw");
const PUBLIC = path.resolve("public/images");
const MEDIA_TS = path.resolve("src/content/media.ts");

function findRaw(key) {
  const dir = path.join(RAW, path.dirname(key));
  if (!fs.existsSync(dir)) return null;
  const base = path.basename(key);
  const file = fs.readdirSync(dir).find((f) => path.parse(f).name === base);
  return file ? path.join(dir, file) : null;
}

const entries = [];
const missing = [];

for (const [key, entry] of Object.entries(assets)) {
  const src = findRaw(key);
  if (!src) {
    missing.push(key);
    continue;
  }
  const ext = entry.keepPng ? "png" : "webp";
  const out = path.join(PUBLIC, `${key}.${ext}`);
  fs.mkdirSync(path.dirname(out), { recursive: true });

  // Keep generous, high-quality sources: next/image re-encodes per device, so avoid double compression.
  const max = entry.keepPng ? entry.max : Math.max(entry.max, 2560);
  let pipeline = sharp(src).rotate().resize({
    width: max,
    height: max,
    fit: "inside",
    withoutEnlargement: true,
  });
  pipeline = entry.keepPng
    ? pipeline.png({ compressionLevel: 9, palette: false })
    : pipeline.webp({ quality: 92, effort: 5, smartSubsample: true });

  const info = await pipeline.toFile(out);
  entries.push({ key, src: `/images/${key}.${ext}`, width: info.width, height: info.height, alt: entry.alt });
  console.log(`${key.padEnd(30)} ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)} KB`);
}

const body = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.key)}: { src: ${JSON.stringify(e.src)}, width: ${e.width}, height: ${e.height}, alt: ${JSON.stringify(e.alt)} },`,
  )
  .join("\n");

fs.writeFileSync(
  MEDIA_TS,
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.\n` +
    `export type MediaAsset = { src: string; width: number; height: number; alt: string };\n\n` +
    `export const media = {\n${body}\n} as const satisfies Record<string, MediaAsset>;\n\n` +
    `export type MediaKey = keyof typeof media;\n`,
);

console.log(`\n${entries.length} images written, ${missing.length} missing.`);
if (missing.length) {
  console.log("Missing:", missing.join(", "));
  process.exitCode = 1;
}
